name: CI on PR

on: [pull_request]

# on: [push]

env:
  APP_NAME: glcp-common-automation-libs
  DC_PROJECT_NAME: glcp-common-automation-libs-ci

  registry: quay.io
  quay_username: ${{ secrets.CCS_QUAY_CCSPORTAL_BUILDER }}
  quay_password: ${{ secrets.CCS_QUAY_CCSPORTAL_BUILDER_PASSWORD }}
  jfrog_user: ${{ secrets.CCS_JFROG_USERNAME }}
  jfrog_passwd: ${{ secrets.CCS_JFROG_PASSWORD }}
  gh_token: ${{ secrets.GLCP_GH_TOKEN }}
  updatectl_user: ${{ secrets.CCS_UPDATECTL_USER }}
  updatectl_server: ${{ secrets.CCS_UPDATECTL_SERVER }}
  updatectl_key: ${{ secrets.CCS_UPDATECTL_KEY }}
  jira_user: ${{ secrets.CCS_JIRA_USER }}
  jira_apikey: ${{ secrets.CCS_JIRA_APIKEY }}

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:

    - name: Run pre-checks
      id: precheck
      uses: glcp/ccs-automation/ci_cd_commons/pr_title_validation@v2
      with:
        pull_request_title: ${{ github.event.pull_request.title }}
        jira_user: ${{ env.jira_user }}
        jira_apikey: ${{ env.jira_apikey }}
        gh_token: ${{ env.gh_token }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Lint
      shell: bash
      run: |
          cd $GITHUB_WORKSPACE
          pip install mypy autoflake black isort
          chmod +x ./scripts/lint.sh
          scripts/lint.sh
